// src/main/webapp/app/entities/messagessms/messagessms-update.tsx
import React, { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate, ValidatedField, ValidatedForm, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { createEntity, getEntity, reset, updateEntity } from './messagessms.reducer';

export const MESSAGESSMSUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const mESSAGESSMSEntity = useAppSelector(state => state.mESSAGESSMS.entity);
  const loading = useAppSelector(state => state.mESSAGESSMS.loading);
  const updating = useAppSelector(state => state.mESSAGESSMS.updating);
  const updateSuccess = useAppSelector(state => state.mESSAGESSMS.updateSuccess);

  const handleClose = () => {
    navigate('/messagessms');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }
    values.tRNDATETIME = convertDateTimeToServer(values.tRNDATETIME);
    if (values.tRIALS !== undefined && typeof values.tRIALS !== 'number') {
      values.tRIALS = Number(values.tRIALS);
    }
    if (values.pRIORITY !== undefined && typeof values.pRIORITY !== 'number') {
      values.pRIORITY = Number(values.pRIORITY);
    }
    if (values.sENT !== undefined && typeof values.sENT !== 'number') {
      values.sENT = Number(values.sENT);
    }
    if (values.dELIVERED !== undefined && typeof values.dELIVERED !== 'number') {
      values.dELIVERED = Number(values.dELIVERED);
    }
    if (values.eRROREXCEPTION !== undefined && typeof values.eRROREXCEPTION !== 'number') {
      values.eRROREXCEPTION = Number(values.eRROREXCEPTION);
    }
    values.dATECREATED = convertDateTimeToServer(values.dATECREATED);
    if (values.tAXPROCESSED !== undefined && typeof values.tAXPROCESSED !== 'number') {
      values.tAXPROCESSED = Number(values.tAXPROCESSED);
    }

    const entity = {
      ...mESSAGESSMSEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          tRNDATETIME: displayDefaultDateTime(),
          dATECREATED: displayDefaultDateTime(),
        }
      : {
          ...mESSAGESSMSEntity,
          tRNDATETIME: convertDateTimeFromServer(mESSAGESSMSEntity.tRNDATETIME),
          dATECREATED: convertDateTimeFromServer(mESSAGESSMSEntity.dATECREATED),
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="bbMobileBankingAdminApp.mESSAGESSMS.home.createOrEditLabel" data-cy="MESSAGESSMSCreateUpdateHeading">
            <Translate contentKey="bbMobileBankingAdminApp.mESSAGESSMS.home.createOrEditLabel">Create or edit a MESSAGESSMS</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="messagessms-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.tRNDATETIME')}
                id="messagessms-tRNDATETIME"
                name="tRNDATETIME"
                data-cy="tRNDATETIME"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.pHONENUMBER')}
                id="messagessms-pHONENUMBER"
                name="pHONENUMBER"
                data-cy="pHONENUMBER"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.tRANSACTIONNO')}
                id="messagessms-tRANSACTIONNO"
                name="tRANSACTIONNO"
                data-cy="tRANSACTIONNO"
                type="text"
                validate={{
                  maxLength: { value: 4000, message: translate('entity.validation.maxlength', { max: 4000 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.aCCOUNTNUMBER')}
                id="messagessms-aCCOUNTNUMBER"
                name="aCCOUNTNUMBER"
                data-cy="aCCOUNTNUMBER"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.mESSAGE')}
                id="messagessms-mESSAGE"
                name="mESSAGE"
                data-cy="mESSAGE"
                type="text"
                validate={{
                  maxLength: { value: 2000, message: translate('entity.validation.maxlength', { max: 2000 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.cHANNEL')}
                id="messagessms-cHANNEL"
                name="cHANNEL"
                data-cy="cHANNEL"
                type="text"
                validate={{
                  maxLength: { value: 4000, message: translate('entity.validation.maxlength', { max: 4000 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.tRIALS')}
                id="messagessms-tRIALS"
                name="tRIALS"
                data-cy="tRIALS"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.pRIORITY')}
                id="messagessms-pRIORITY"
                name="pRIORITY"
                data-cy="pRIORITY"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.rESPONSECODE')}
                id="messagessms-rESPONSECODE"
                name="rESPONSECODE"
                data-cy="rESPONSECODE"
                type="text"
                validate={{
                  maxLength: { value: 4, message: translate('entity.validation.maxlength', { max: 4 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.rESPONSEMSG')}
                id="messagessms-rESPONSEMSG"
                name="rESPONSEMSG"
                data-cy="rESPONSEMSG"
                type="text"
                validate={{
                  maxLength: { value: 4000, message: translate('entity.validation.maxlength', { max: 4000 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.sENT')}
                id="messagessms-sENT"
                name="sENT"
                data-cy="sENT"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.dELIVERED')}
                id="messagessms-dELIVERED"
                name="dELIVERED"
                data-cy="dELIVERED"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.tXNTYPE')}
                id="messagessms-tXNTYPE"
                name="tXNTYPE"
                data-cy="tXNTYPE"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.eRROREXCEPTION')}
                id="messagessms-eRROREXCEPTION"
                name="eRROREXCEPTION"
                data-cy="eRROREXCEPTION"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.dATECREATED')}
                id="messagessms-dATECREATED"
                name="dATECREATED"
                data-cy="dATECREATED"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.dATESENT')}
                id="messagessms-dATESENT"
                name="dATESENT"
                data-cy="dATESENT"
                type="text"
                validate={{
                  maxLength: { value: 7, message: translate('entity.validation.maxlength', { max: 7 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.rTPSREQTIME')}
                id="messagessms-rTPSREQTIME"
                name="rTPSREQTIME"
                data-cy="rTPSREQTIME"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.fXGENERATED')}
                id="messagessms-fXGENERATED"
                name="fXGENERATED"
                data-cy="fXGENERATED"
                type="text"
                validate={{
                  maxLength: { value: 20, message: translate('entity.validation.maxlength', { max: 20 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.tAXPROCESSED')}
                id="messagessms-tAXPROCESSED"
                name="tAXPROCESSED"
                data-cy="tAXPROCESSED"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.bATCHNUMBER')}
                id="messagessms-bATCHNUMBER"
                name="bATCHNUMBER"
                data-cy="bATCHNUMBER"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.bATCHNUMBERTAX')}
                id="messagessms-bATCHNUMBERTAX"
                name="bATCHNUMBERTAX"
                data-cy="bATCHNUMBERTAX"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.rESPONSETIME')}
                id="messagessms-rESPONSETIME"
                name="rESPONSETIME"
                data-cy="rESPONSETIME"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.pDUSEQID')}
                id="messagessms-pDUSEQID"
                name="pDUSEQID"
                data-cy="pDUSEQID"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.rEMARKS')}
                id="messagessms-rEMARKS"
                name="rEMARKS"
                data-cy="rEMARKS"
                type="text"
                validate={{
                  maxLength: { value: 300, message: translate('entity.validation.maxlength', { max: 300 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.mESSAGESSMS.rESENDBY')}
                id="messagessms-rESENDBY"
                name="rESENDBY"
                data-cy="rESENDBY"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/messagessms" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default MESSAGESSMSUpdate;

// src/main/webapp/app/entities/messages-sms/messages-sms-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" novalidate @submit.prevent="save()">
        <h2
          id="bbMobileBankingAdminApp.messagesSms.home.createOrEditLabel"
          data-cy="MessagesSmsCreateUpdateHeading"
          v-text="t$('bbMobileBankingAdminApp.messagesSms.home.createOrEditLabel')"
        ></h2>
        <div>
          <div class="form-group" v-if="messagesSms.id">
            <label for="id" v-text="t$('global.field.id')"></label>
            <input type="text" class="form-control" id="id" name="id" v-model="messagesSms.id" readonly />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.trndatetime')"
              for="messages-sms-trndatetime"
            ></label>
            <div class="d-flex">
              <input
                id="messages-sms-trndatetime"
                data-cy="trndatetime"
                type="datetime-local"
                class="form-control"
                name="trndatetime"
                :class="{ valid: !v$.trndatetime.$invalid, invalid: v$.trndatetime.$invalid }"
                :value="convertDateTimeFromServer(v$.trndatetime.$model)"
                @change="updateInstantField('trndatetime', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.phonenumber')"
              for="messages-sms-phonenumber"
            ></label>
            <input
              type="text"
              class="form-control"
              name="phonenumber"
              id="messages-sms-phonenumber"
              data-cy="phonenumber"
              :class="{ valid: !v$.phonenumber.$invalid, invalid: v$.phonenumber.$invalid }"
              v-model="v$.phonenumber.$model"
            />
            <div v-if="v$.phonenumber.$anyDirty && v$.phonenumber.$invalid">
              <small class="form-text text-danger" v-for="error of v$.phonenumber.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.transactionno')"
              for="messages-sms-transactionno"
            ></label>
            <input
              type="text"
              class="form-control"
              name="transactionno"
              id="messages-sms-transactionno"
              data-cy="transactionno"
              :class="{ valid: !v$.transactionno.$invalid, invalid: v$.transactionno.$invalid }"
              v-model="v$.transactionno.$model"
            />
            <div v-if="v$.transactionno.$anyDirty && v$.transactionno.$invalid">
              <small class="form-text text-danger" v-for="error of v$.transactionno.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.accountnumber')"
              for="messages-sms-accountnumber"
            ></label>
            <input
              type="text"
              class="form-control"
              name="accountnumber"
              id="messages-sms-accountnumber"
              data-cy="accountnumber"
              :class="{ valid: !v$.accountnumber.$invalid, invalid: v$.accountnumber.$invalid }"
              v-model="v$.accountnumber.$model"
            />
            <div v-if="v$.accountnumber.$anyDirty && v$.accountnumber.$invalid">
              <small class="form-text text-danger" v-for="error of v$.accountnumber.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.messagesSms.message')" for="messages-sms-message"></label>
            <input
              type="text"
              class="form-control"
              name="message"
              id="messages-sms-message"
              data-cy="message"
              :class="{ valid: !v$.message.$invalid, invalid: v$.message.$invalid }"
              v-model="v$.message.$model"
            />
            <div v-if="v$.message.$anyDirty && v$.message.$invalid">
              <small class="form-text text-danger" v-for="error of v$.message.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.messagesSms.channel')" for="messages-sms-channel"></label>
            <input
              type="text"
              class="form-control"
              name="channel"
              id="messages-sms-channel"
              data-cy="channel"
              :class="{ valid: !v$.channel.$invalid, invalid: v$.channel.$invalid }"
              v-model="v$.channel.$model"
            />
            <div v-if="v$.channel.$anyDirty && v$.channel.$invalid">
              <small class="form-text text-danger" v-for="error of v$.channel.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.messagesSms.trials')" for="messages-sms-trials"></label>
            <input
              type="number"
              class="form-control"
              name="trials"
              id="messages-sms-trials"
              data-cy="trials"
              :class="{ valid: !v$.trials.$invalid, invalid: v$.trials.$invalid }"
              v-model.number="v$.trials.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.priority')"
              for="messages-sms-priority"
            ></label>
            <input
              type="number"
              class="form-control"
              name="priority"
              id="messages-sms-priority"
              data-cy="priority"
              :class="{ valid: !v$.priority.$invalid, invalid: v$.priority.$invalid }"
              v-model.number="v$.priority.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.responsecode')"
              for="messages-sms-responsecode"
            ></label>
            <input
              type="text"
              class="form-control"
              name="responsecode"
              id="messages-sms-responsecode"
              data-cy="responsecode"
              :class="{ valid: !v$.responsecode.$invalid, invalid: v$.responsecode.$invalid }"
              v-model="v$.responsecode.$model"
            />
            <div v-if="v$.responsecode.$anyDirty && v$.responsecode.$invalid">
              <small class="form-text text-danger" v-for="error of v$.responsecode.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.responsemsg')"
              for="messages-sms-responsemsg"
            ></label>
            <input
              type="text"
              class="form-control"
              name="responsemsg"
              id="messages-sms-responsemsg"
              data-cy="responsemsg"
              :class="{ valid: !v$.responsemsg.$invalid, invalid: v$.responsemsg.$invalid }"
              v-model="v$.responsemsg.$model"
            />
            <div v-if="v$.responsemsg.$anyDirty && v$.responsemsg.$invalid">
              <small class="form-text text-danger" v-for="error of v$.responsemsg.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.messagesSms.sent')" for="messages-sms-sent"></label>
            <input
              type="number"
              class="form-control"
              name="sent"
              id="messages-sms-sent"
              data-cy="sent"
              :class="{ valid: !v$.sent.$invalid, invalid: v$.sent.$invalid }"
              v-model.number="v$.sent.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.delivered')"
              for="messages-sms-delivered"
            ></label>
            <input
              type="number"
              class="form-control"
              name="delivered"
              id="messages-sms-delivered"
              data-cy="delivered"
              :class="{ valid: !v$.delivered.$invalid, invalid: v$.delivered.$invalid }"
              v-model.number="v$.delivered.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.messagesSms.txntype')" for="messages-sms-txntype"></label>
            <input
              type="text"
              class="form-control"
              name="txntype"
              id="messages-sms-txntype"
              data-cy="txntype"
              :class="{ valid: !v$.txntype.$invalid, invalid: v$.txntype.$invalid }"
              v-model="v$.txntype.$model"
            />
            <div v-if="v$.txntype.$anyDirty && v$.txntype.$invalid">
              <small class="form-text text-danger" v-for="error of v$.txntype.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.errorexception')"
              for="messages-sms-errorexception"
            ></label>
            <input
              type="number"
              class="form-control"
              name="errorexception"
              id="messages-sms-errorexception"
              data-cy="errorexception"
              :class="{ valid: !v$.errorexception.$invalid, invalid: v$.errorexception.$invalid }"
              v-model.number="v$.errorexception.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.datecreated')"
              for="messages-sms-datecreated"
            ></label>
            <div class="d-flex">
              <input
                id="messages-sms-datecreated"
                data-cy="datecreated"
                type="datetime-local"
                class="form-control"
                name="datecreated"
                :class="{ valid: !v$.datecreated.$invalid, invalid: v$.datecreated.$invalid }"
                :value="convertDateTimeFromServer(v$.datecreated.$model)"
                @change="updateInstantField('datecreated', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.datesent')"
              for="messages-sms-datesent"
            ></label>
            <input
              type="text"
              class="form-control"
              name="datesent"
              id="messages-sms-datesent"
              data-cy="datesent"
              :class="{ valid: !v$.datesent.$invalid, invalid: v$.datesent.$invalid }"
              v-model="v$.datesent.$model"
            />
            <div v-if="v$.datesent.$anyDirty && v$.datesent.$invalid">
              <small class="form-text text-danger" v-for="error of v$.datesent.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.rtpsreqtime')"
              for="messages-sms-rtpsreqtime"
            ></label>
            <input
              type="text"
              class="form-control"
              name="rtpsreqtime"
              id="messages-sms-rtpsreqtime"
              data-cy="rtpsreqtime"
              :class="{ valid: !v$.rtpsreqtime.$invalid, invalid: v$.rtpsreqtime.$invalid }"
              v-model="v$.rtpsreqtime.$model"
            />
            <div v-if="v$.rtpsreqtime.$anyDirty && v$.rtpsreqtime.$invalid">
              <small class="form-text text-danger" v-for="error of v$.rtpsreqtime.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.fxgenerated')"
              for="messages-sms-fxgenerated"
            ></label>
            <input
              type="text"
              class="form-control"
              name="fxgenerated"
              id="messages-sms-fxgenerated"
              data-cy="fxgenerated"
              :class="{ valid: !v$.fxgenerated.$invalid, invalid: v$.fxgenerated.$invalid }"
              v-model="v$.fxgenerated.$model"
            />
            <div v-if="v$.fxgenerated.$anyDirty && v$.fxgenerated.$invalid">
              <small class="form-text text-danger" v-for="error of v$.fxgenerated.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.taxprocessed')"
              for="messages-sms-taxprocessed"
            ></label>
            <input
              type="number"
              class="form-control"
              name="taxprocessed"
              id="messages-sms-taxprocessed"
              data-cy="taxprocessed"
              :class="{ valid: !v$.taxprocessed.$invalid, invalid: v$.taxprocessed.$invalid }"
              v-model.number="v$.taxprocessed.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.batchnumber')"
              for="messages-sms-batchnumber"
            ></label>
            <input
              type="text"
              class="form-control"
              name="batchnumber"
              id="messages-sms-batchnumber"
              data-cy="batchnumber"
              :class="{ valid: !v$.batchnumber.$invalid, invalid: v$.batchnumber.$invalid }"
              v-model="v$.batchnumber.$model"
            />
            <div v-if="v$.batchnumber.$anyDirty && v$.batchnumber.$invalid">
              <small class="form-text text-danger" v-for="error of v$.batchnumber.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.batchnumbertax')"
              for="messages-sms-batchnumbertax"
            ></label>
            <input
              type="text"
              class="form-control"
              name="batchnumbertax"
              id="messages-sms-batchnumbertax"
              data-cy="batchnumbertax"
              :class="{ valid: !v$.batchnumbertax.$invalid, invalid: v$.batchnumbertax.$invalid }"
              v-model="v$.batchnumbertax.$model"
            />
            <div v-if="v$.batchnumbertax.$anyDirty && v$.batchnumbertax.$invalid">
              <small class="form-text text-danger" v-for="error of v$.batchnumbertax.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.responsetime')"
              for="messages-sms-responsetime"
            ></label>
            <input
              type="text"
              class="form-control"
              name="responsetime"
              id="messages-sms-responsetime"
              data-cy="responsetime"
              :class="{ valid: !v$.responsetime.$invalid, invalid: v$.responsetime.$invalid }"
              v-model="v$.responsetime.$model"
            />
            <div v-if="v$.responsetime.$anyDirty && v$.responsetime.$invalid">
              <small class="form-text text-danger" v-for="error of v$.responsetime.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.pduseqid')"
              for="messages-sms-pduseqid"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pduseqid"
              id="messages-sms-pduseqid"
              data-cy="pduseqid"
              :class="{ valid: !v$.pduseqid.$invalid, invalid: v$.pduseqid.$invalid }"
              v-model="v$.pduseqid.$model"
            />
            <div v-if="v$.pduseqid.$anyDirty && v$.pduseqid.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pduseqid.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.messagesSms.remarks')" for="messages-sms-remarks"></label>
            <input
              type="text"
              class="form-control"
              name="remarks"
              id="messages-sms-remarks"
              data-cy="remarks"
              :class="{ valid: !v$.remarks.$invalid, invalid: v$.remarks.$invalid }"
              v-model="v$.remarks.$model"
            />
            <div v-if="v$.remarks.$anyDirty && v$.remarks.$invalid">
              <small class="form-text text-danger" v-for="error of v$.remarks.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.messagesSms.resendby')"
              for="messages-sms-resendby"
            ></label>
            <input
              type="text"
              class="form-control"
              name="resendby"
              id="messages-sms-resendby"
              data-cy="resendby"
              :class="{ valid: !v$.resendby.$invalid, invalid: v$.resendby.$invalid }"
              v-model="v$.resendby.$model"
            />
            <div v-if="v$.resendby.$anyDirty && v$.resendby.$invalid">
              <small class="form-text text-danger" v-for="error of v$.resendby.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" @click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.cancel')"></span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="v$.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.save')"></span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./messages-sms-update.component.ts"></script>
