// src/main/webapp/app/entities/billers/billers.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="BillersHeading">
      <span v-text="t$('bbMobileBankingAdminApp.billers.home.title')" id="billers-heading"></span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" @click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="t$('bbMobileBankingAdminApp.billers.home.refreshListLabel')"></span>
        </button>
        <router-link :to="{ name: 'BillersCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-billers"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="t$('bbMobileBankingAdminApp.billers.home.createLabel')"></span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && billers && billers.length === 0">
      <span v-text="t$('bbMobileBankingAdminApp.billers.home.notFound')"></span>
    </div>
    <div class="table-responsive" v-if="billers && billers.length > 0">
      <table class="table table-striped" aria-describedby="billers">
        <thead>
          <tr>
            <th scope="row"><span v-text="t$('global.field.id')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.billerid')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.description')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.billercollectionaccount')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.datecreated')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.createdby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.approved')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.approvedby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.approveddate')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.chargableproductid')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.nonchargableproductid')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.usdbillercollectionaccount')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.enableduplicatecheck')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.remarks')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.sessionid')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.reworkby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.status')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.active')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.billers.rework')"></span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="billers in billers" :key="billers.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'BillersView', params: { billersId: billers.id } }">{{ billers.id }}</router-link>
            </td>
            <td>{{ billers.billerid }}</td>
            <td>{{ billers.description }}</td>
            <td>{{ billers.billercollectionaccount }}</td>
            <td>{{ formatDateShort(billers.datecreated) || '' }}</td>
            <td>{{ billers.createdby }}</td>
            <td>{{ billers.approved }}</td>
            <td>{{ billers.approvedby }}</td>
            <td>{{ formatDateShort(billers.approveddate) || '' }}</td>
            <td>{{ billers.chargableproductid }}</td>
            <td>{{ billers.nonchargableproductid }}</td>
            <td>{{ billers.usdbillercollectionaccount }}</td>
            <td>{{ billers.enableduplicatecheck }}</td>
            <td>{{ billers.remarks }}</td>
            <td>{{ billers.sessionid }}</td>
            <td>{{ billers.reworkby }}</td>
            <td>{{ billers.status }}</td>
            <td>{{ billers.active }}</td>
            <td>{{ billers.rework }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link :to="{ name: 'BillersView', params: { billersId: billers.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="t$('entity.action.view')"></span>
                  </button>
                </router-link>
                <router-link :to="{ name: 'BillersEdit', params: { billersId: billers.id } }" custom v-slot="{ navigate }">
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="t$('entity.action.edit')"></span>
                  </button>
                </router-link>
                <b-button
                  @click="prepareRemove(billers)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="t$('entity.action.delete')"></span>
                </b-button>
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <template #modal-title>
        <span
          id="bbMobileBankingAdminApp.billers.delete.question"
          data-cy="billersDeleteDialogHeading"
          v-text="t$('entity.delete.title')"
        ></span>
      </template>
      <div class="modal-body">
        <p id="jhi-delete-billers-heading" v-text="t$('bbMobileBankingAdminApp.billers.delete.question', { id: removeId })"></p>
      </div>
      <template #modal-footer>
        <div>
          <button type="button" class="btn btn-secondary" v-text="t$('entity.action.cancel')" @click="closeDialog()"></button>
          <button
            type="button"
            class="btn btn-primary"
            id="jhi-confirm-delete-billers"
            data-cy="entityConfirmDeleteButton"
            v-text="t$('entity.action.delete')"
            @click="removeBillers()"
          ></button>
        </div>
      </template>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./billers.component.ts"></script>

// src/main/webapp/app/entities/billers/billers.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { TextFormat, Translate, getSortState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { APP_DATE_FORMAT } from 'app/config/constants';
import { ASC, DESC } from 'app/shared/util/pagination.constants';
import { overrideSortStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './billers.reducer';

export const BILLERS = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [sortState, setSortState] = useState(overrideSortStateWithQueryParams(getSortState(pageLocation, 'id'), pageLocation.search));

  const bILLERSList = useAppSelector(state => state.bILLERS.entities);
  const loading = useAppSelector(state => state.bILLERS.loading);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        sort: `${sortState.sort},${sortState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?sort=${sortState.sort},${sortState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [sortState.order, sortState.sort]);

  const sort = p => () => {
    setSortState({
      ...sortState,
      order: sortState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = sortState.sort;
    const order = sortState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="billers-heading" data-cy="BILLERSHeading">
        <Translate contentKey="bbMobileBankingAdminApp.bILLERS.home.title">BILLERS</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="bbMobileBankingAdminApp.bILLERS.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/billers/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="bbMobileBankingAdminApp.bILLERS.home.createLabel">Create new BILLERS</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {bILLERSList && bILLERSList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.id">ID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('bILLERID')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.bILLERID">B ILLERID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('bILLERID')} />
                </th>
                <th className="hand" onClick={sort('dESCRIPTION')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.dESCRIPTION">D ESCRIPTION</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('dESCRIPTION')} />
                </th>
                <th className="hand" onClick={sort('bILLERCOLLECTIONACCOUNT')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.bILLERCOLLECTIONACCOUNT">B ILLERCOLLECTIONACCOUNT</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('bILLERCOLLECTIONACCOUNT')} />
                </th>
                <th className="hand" onClick={sort('dATECREATED')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.dATECREATED">D ATECREATED</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('dATECREATED')} />
                </th>
                <th className="hand" onClick={sort('cREATEDBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.cREATEDBY">C REATEDBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('cREATEDBY')} />
                </th>
                <th className="hand" onClick={sort('aPPROVED')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.aPPROVED">A PPROVED</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aPPROVED')} />
                </th>
                <th className="hand" onClick={sort('aPPROVEDBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.aPPROVEDBY">A PPROVEDBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aPPROVEDBY')} />
                </th>
                <th className="hand" onClick={sort('aPPROVEDDATE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.aPPROVEDDATE">A PPROVEDDATE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aPPROVEDDATE')} />
                </th>
                <th className="hand" onClick={sort('cHARGABLEPRODUCTID')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.cHARGABLEPRODUCTID">C HARGABLEPRODUCTID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('cHARGABLEPRODUCTID')} />
                </th>
                <th className="hand" onClick={sort('nONCHARGABLEPRODUCTID')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.nONCHARGABLEPRODUCTID">N ONCHARGABLEPRODUCTID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('nONCHARGABLEPRODUCTID')} />
                </th>
                <th className="hand" onClick={sort('uSDBILLERCOLLECTIONACCOUNT')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.uSDBILLERCOLLECTIONACCOUNT">U SDBILLERCOLLECTIONACCOUNT</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('uSDBILLERCOLLECTIONACCOUNT')} />
                </th>
                <th className="hand" onClick={sort('eNABLEDUPLICATECHECK')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.eNABLEDUPLICATECHECK">E NABLEDUPLICATECHECK</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('eNABLEDUPLICATECHECK')} />
                </th>
                <th className="hand" onClick={sort('rEMARKS')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.rEMARKS">R EMARKS</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('rEMARKS')} />
                </th>
                <th className="hand" onClick={sort('sESSIONID')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.sESSIONID">S ESSIONID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('sESSIONID')} />
                </th>
                <th className="hand" onClick={sort('rEWORKBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.rEWORKBY">R EWORKBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('rEWORKBY')} />
                </th>
                <th className="hand" onClick={sort('sTATUS')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.sTATUS">S TATUS</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('sTATUS')} />
                </th>
                <th className="hand" onClick={sort('aCTIVE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.aCTIVE">A CTIVE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aCTIVE')} />
                </th>
                <th className="hand" onClick={sort('rEWORK')}>
                  <Translate contentKey="bbMobileBankingAdminApp.bILLERS.rEWORK">R EWORK</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('rEWORK')} />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {bILLERSList.map((bILLERS, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/billers/${bILLERS.id}`} color="link" size="sm">
                      {bILLERS.id}
                    </Button>
                  </td>
                  <td>{bILLERS.bILLERID}</td>
                  <td>{bILLERS.dESCRIPTION}</td>
                  <td>{bILLERS.bILLERCOLLECTIONACCOUNT}</td>
                  <td>{bILLERS.dATECREATED ? <TextFormat type="date" value={bILLERS.dATECREATED} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{bILLERS.cREATEDBY}</td>
                  <td>{bILLERS.aPPROVED}</td>
                  <td>{bILLERS.aPPROVEDBY}</td>
                  <td>{bILLERS.aPPROVEDDATE ? <TextFormat type="date" value={bILLERS.aPPROVEDDATE} format={APP_DATE_FORMAT} /> : null}</td>
                  <td>{bILLERS.cHARGABLEPRODUCTID}</td>
                  <td>{bILLERS.nONCHARGABLEPRODUCTID}</td>
                  <td>{bILLERS.uSDBILLERCOLLECTIONACCOUNT}</td>
                  <td>{bILLERS.eNABLEDUPLICATECHECK}</td>
                  <td>{bILLERS.rEMARKS}</td>
                  <td>{bILLERS.sESSIONID}</td>
                  <td>{bILLERS.rEWORKBY}</td>
                  <td>{bILLERS.sTATUS}</td>
                  <td>{bILLERS.aCTIVE}</td>
                  <td>{bILLERS.rEWORK}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/billers/${bILLERS.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button tag={Link} to={`/billers/${bILLERS.id}/edit`} color="primary" size="sm" data-cy="entityEditButton">
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() => (window.location.href = `/billers/${bILLERS.id}/delete`)}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="bbMobileBankingAdminApp.bILLERS.home.notFound">No BILLERS found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default BILLERS;
