// src/main/webapp/app/entities/pin-reset-history/pin-reset-history-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" novalidate @submit.prevent="save()">
        <h2
          id="bbMobileBankingAdminApp.pinResetHistory.home.createOrEditLabel"
          data-cy="PinResetHistoryCreateUpdateHeading"
          v-text="t$('bbMobileBankingAdminApp.pinResetHistory.home.createOrEditLabel')"
        ></h2>
        <div>
          <div class="form-group" v-if="pinResetHistory.id">
            <label for="id" v-text="t$('global.field.id')"></label>
            <input type="text" class="form-control" id="id" name="id" v-model="pinResetHistory.id" readonly />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.phonenumber')"
              for="pin-reset-history-phonenumber"
            ></label>
            <input
              type="text"
              class="form-control"
              name="phonenumber"
              id="pin-reset-history-phonenumber"
              data-cy="phonenumber"
              :class="{ valid: !v$.phonenumber.$invalid, invalid: v$.phonenumber.$invalid }"
              v-model="v$.phonenumber.$model"
            />
            <div v-if="v$.phonenumber.$anyDirty && v$.phonenumber.$invalid">
              <small class="form-text text-danger" v-for="error of v$.phonenumber.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.customername')"
              for="pin-reset-history-customername"
            ></label>
            <input
              type="text"
              class="form-control"
              name="customername"
              id="pin-reset-history-customername"
              data-cy="customername"
              :class="{ valid: !v$.customername.$invalid, invalid: v$.customername.$invalid }"
              v-model="v$.customername.$model"
            />
            <div v-if="v$.customername.$anyDirty && v$.customername.$invalid">
              <small class="form-text text-danger" v-for="error of v$.customername.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinblockedon')"
              for="pin-reset-history-pinblockedon"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinblockedon"
              id="pin-reset-history-pinblockedon"
              data-cy="pinblockedon"
              :class="{ valid: !v$.pinblockedon.$invalid, invalid: v$.pinblockedon.$invalid }"
              v-model="v$.pinblockedon.$model"
            />
            <div v-if="v$.pinblockedon.$anyDirty && v$.pinblockedon.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinblockedon.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinblockremarks')"
              for="pin-reset-history-pinblockremarks"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinblockremarks"
              id="pin-reset-history-pinblockremarks"
              data-cy="pinblockremarks"
              :class="{ valid: !v$.pinblockremarks.$invalid, invalid: v$.pinblockremarks.$invalid }"
              v-model="v$.pinblockremarks.$model"
            />
            <div v-if="v$.pinblockremarks.$anyDirty && v$.pinblockremarks.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinblockremarks.$errors" :key="error.$uid">{{
                error.$message
              }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetby')"
              for="pin-reset-history-pinresetby"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinresetby"
              id="pin-reset-history-pinresetby"
              data-cy="pinresetby"
              :class="{ valid: !v$.pinresetby.$invalid, invalid: v$.pinresetby.$invalid }"
              v-model="v$.pinresetby.$model"
            />
            <div v-if="v$.pinresetby.$anyDirty && v$.pinresetby.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinresetby.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinreseton')"
              for="pin-reset-history-pinreseton"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinreseton"
              id="pin-reset-history-pinreseton"
              data-cy="pinreseton"
              :class="{ valid: !v$.pinreseton.$invalid, invalid: v$.pinreseton.$invalid }"
              v-model="v$.pinreseton.$model"
            />
            <div v-if="v$.pinreseton.$anyDirty && v$.pinreseton.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinreseton.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetapprovedby')"
              for="pin-reset-history-pinresetapprovedby"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinresetapprovedby"
              id="pin-reset-history-pinresetapprovedby"
              data-cy="pinresetapprovedby"
              :class="{ valid: !v$.pinresetapprovedby.$invalid, invalid: v$.pinresetapprovedby.$invalid }"
              v-model="v$.pinresetapprovedby.$model"
            />
            <div v-if="v$.pinresetapprovedby.$anyDirty && v$.pinresetapprovedby.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinresetapprovedby.$errors" :key="error.$uid">{{
                error.$message
              }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetapprovedon')"
              for="pin-reset-history-pinresetapprovedon"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinresetapprovedon"
              id="pin-reset-history-pinresetapprovedon"
              data-cy="pinresetapprovedon"
              :class="{ valid: !v$.pinresetapprovedon.$invalid, invalid: v$.pinresetapprovedon.$invalid }"
              v-model="v$.pinresetapprovedon.$model"
            />
            <div v-if="v$.pinresetapprovedon.$anyDirty && v$.pinresetapprovedon.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinresetapprovedon.$errors" :key="error.$uid">{{
                error.$message
              }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetremarks')"
              for="pin-reset-history-pinresetremarks"
            ></label>
            <input
              type="text"
              class="form-control"
              name="pinresetremarks"
              id="pin-reset-history-pinresetremarks"
              data-cy="pinresetremarks"
              :class="{ valid: !v$.pinresetremarks.$invalid, invalid: v$.pinresetremarks.$invalid }"
              v-model="v$.pinresetremarks.$model"
            />
            <div v-if="v$.pinresetremarks.$anyDirty && v$.pinresetremarks.$invalid">
              <small class="form-text text-danger" v-for="error of v$.pinresetremarks.$errors" :key="error.$uid">{{
                error.$message
              }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.pinResetHistory.branchcode')"
              for="pin-reset-history-branchcode"
            ></label>
            <input
              type="text"
              class="form-control"
              name="branchcode"
              id="pin-reset-history-branchcode"
              data-cy="branchcode"
              :class="{ valid: !v$.branchcode.$invalid, invalid: v$.branchcode.$invalid }"
              v-model="v$.branchcode.$model"
            />
            <div v-if="v$.branchcode.$anyDirty && v$.branchcode.$invalid">
              <small class="form-text text-danger" v-for="error of v$.branchcode.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" @click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.cancel')"></span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="v$.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.save')"></span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./pin-reset-history-update.component.ts"></script>

// src/main/webapp/app/entities/pinresethistory/pinresethistory-update.tsx
import React, { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate, ValidatedField, ValidatedForm, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { createEntity, getEntity, reset, updateEntity } from './pinresethistory.reducer';

export const PINRESETHISTORYUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const pINRESETHISTORYEntity = useAppSelector(state => state.pINRESETHISTORY.entity);
  const loading = useAppSelector(state => state.pINRESETHISTORY.loading);
  const updating = useAppSelector(state => state.pINRESETHISTORY.updating);
  const updateSuccess = useAppSelector(state => state.pINRESETHISTORY.updateSuccess);

  const handleClose = () => {
    navigate('/pinresethistory');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }

    const entity = {
      ...pINRESETHISTORYEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...pINRESETHISTORYEntity,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="bbMobileBankingAdminApp.pINRESETHISTORY.home.createOrEditLabel" data-cy="PINRESETHISTORYCreateUpdateHeading">
            <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.home.createOrEditLabel">
              Create or edit a PINRESETHISTORY
            </Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="pinresethistory-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pHONENUMBER')}
                id="pinresethistory-pHONENUMBER"
                name="pHONENUMBER"
                data-cy="pHONENUMBER"
                type="text"
                validate={{
                  maxLength: { value: 20, message: translate('entity.validation.maxlength', { max: 20 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.cUSTOMERNAME')}
                id="pinresethistory-cUSTOMERNAME"
                name="cUSTOMERNAME"
                data-cy="cUSTOMERNAME"
                type="text"
                validate={{
                  maxLength: { value: 150, message: translate('entity.validation.maxlength', { max: 150 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINBLOCKEDON')}
                id="pinresethistory-pINBLOCKEDON"
                name="pINBLOCKEDON"
                data-cy="pINBLOCKEDON"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINBLOCKREMARKS')}
                id="pinresethistory-pINBLOCKREMARKS"
                name="pINBLOCKREMARKS"
                data-cy="pINBLOCKREMARKS"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETBY')}
                id="pinresethistory-pINRESETBY"
                name="pINRESETBY"
                data-cy="pINRESETBY"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETON')}
                id="pinresethistory-pINRESETON"
                name="pINRESETON"
                data-cy="pINRESETON"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETAPPROVEDBY')}
                id="pinresethistory-pINRESETAPPROVEDBY"
                name="pINRESETAPPROVEDBY"
                data-cy="pINRESETAPPROVEDBY"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETAPPROVEDON')}
                id="pinresethistory-pINRESETAPPROVEDON"
                name="pINRESETAPPROVEDON"
                data-cy="pINRESETAPPROVEDON"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETREMARKS')}
                id="pinresethistory-pINRESETREMARKS"
                name="pINRESETREMARKS"
                data-cy="pINRESETREMARKS"
                type="text"
                validate={{
                  maxLength: { value: 200, message: translate('entity.validation.maxlength', { max: 200 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.pINRESETHISTORY.bRANCHCODE')}
                id="pinresethistory-bRANCHCODE"
                name="bRANCHCODE"
                data-cy="bRANCHCODE"
                type="text"
                validate={{
                  maxLength: { value: 20, message: translate('entity.validation.maxlength', { max: 20 }) },
                }}
              />
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/pinresethistory" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default PINRESETHISTORYUpdate;
