// src/main/webapp/app/entities/pin-reset-history/pin-reset-history.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="PinResetHistoryHeading">
      <span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.home.title')" id="pin-reset-history-heading"></span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" @click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.home.refreshListLabel')"></span>
        </button>
        <router-link :to="{ name: 'PinResetHistoryCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-pin-reset-history"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.home.createLabel')"></span>
          </button>
        </router-link>
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && pinResetHistories && pinResetHistories.length === 0">
      <span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.home.notFound')"></span>
    </div>
    <div class="table-responsive" v-if="pinResetHistories && pinResetHistories.length > 0">
      <table class="table table-striped" aria-describedby="pinResetHistories">
        <thead>
          <tr>
            <th scope="row"><span v-text="t$('global.field.id')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.phonenumber')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.customername')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinblockedon')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinblockremarks')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinreseton')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetapprovedby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetapprovedon')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.pinresetremarks')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.pinResetHistory.branchcode')"></span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="pinResetHistory in pinResetHistories" :key="pinResetHistory.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'PinResetHistoryView', params: { pinResetHistoryId: pinResetHistory.id } }">{{
                pinResetHistory.id
              }}</router-link>
            </td>
            <td>{{ pinResetHistory.phonenumber }}</td>
            <td>{{ pinResetHistory.customername }}</td>
            <td>{{ pinResetHistory.pinblockedon }}</td>
            <td>{{ pinResetHistory.pinblockremarks }}</td>
            <td>{{ pinResetHistory.pinresetby }}</td>
            <td>{{ pinResetHistory.pinreseton }}</td>
            <td>{{ pinResetHistory.pinresetapprovedby }}</td>
            <td>{{ pinResetHistory.pinresetapprovedon }}</td>
            <td>{{ pinResetHistory.pinresetremarks }}</td>
            <td>{{ pinResetHistory.branchcode }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link
                  :to="{ name: 'PinResetHistoryView', params: { pinResetHistoryId: pinResetHistory.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="t$('entity.action.view')"></span>
                  </button>
                </router-link>
                <!-- <router-link
                  :to="{ name: 'PinResetHistoryEdit', params: { pinResetHistoryId: pinResetHistory.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="t$('entity.action.edit')"></span>
                  </button>
                </router-link> -->
                <!-- <b-button
                  @click="prepareRemove(pinResetHistory)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="t$('entity.action.delete')"></span>
                </b-button> -->
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <template #modal-title>
        <span
          id="bbMobileBankingAdminApp.pinResetHistory.delete.question"
          data-cy="pinResetHistoryDeleteDialogHeading"
          v-text="t$('entity.delete.title')"
        ></span>
      </template>
      <div class="modal-body">
        <p
          id="jhi-delete-pinResetHistory-heading"
          v-text="t$('bbMobileBankingAdminApp.pinResetHistory.delete.question', { id: removeId })"
        ></p>
      </div>
      <template #modal-footer>
        <div>
          <button type="button" class="btn btn-secondary" v-text="t$('entity.action.cancel')" @click="closeDialog()"></button>
          <button
            type="button"
            class="btn btn-primary"
            id="jhi-confirm-delete-pinResetHistory"
            data-cy="entityConfirmDeleteButton"
            v-text="t$('entity.action.delete')"
            @click="removePinResetHistory()"
          ></button>
        </div>
      </template>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./pin-reset-history.component.ts"></script>

// src/main/webapp/app/entities/pinresethistory/pinresethistory.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { Translate, getSortState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { ASC, DESC } from 'app/shared/util/pagination.constants';
import { overrideSortStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './pinresethistory.reducer';

export const PINRESETHISTORY = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [sortState, setSortState] = useState(overrideSortStateWithQueryParams(getSortState(pageLocation, 'id'), pageLocation.search));

  const pINRESETHISTORYList = useAppSelector(state => state.pINRESETHISTORY.entities);
  const loading = useAppSelector(state => state.pINRESETHISTORY.loading);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        sort: `${sortState.sort},${sortState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?sort=${sortState.sort},${sortState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [sortState.order, sortState.sort]);

  const sort = p => () => {
    setSortState({
      ...sortState,
      order: sortState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = sortState.sort;
    const order = sortState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="pinresethistory-heading" data-cy="PINRESETHISTORYHeading">
        <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.home.title">PINRESETHISTORIES</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/pinresethistory/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.home.createLabel">Create new PINRESETHISTORY</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {pINRESETHISTORYList && pINRESETHISTORYList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.id">ID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('pHONENUMBER')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pHONENUMBER">P HONENUMBER</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pHONENUMBER')} />
                </th>
                <th className="hand" onClick={sort('cUSTOMERNAME')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.cUSTOMERNAME">C USTOMERNAME</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('cUSTOMERNAME')} />
                </th>
                <th className="hand" onClick={sort('pINBLOCKEDON')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINBLOCKEDON">P INBLOCKEDON</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINBLOCKEDON')} />
                </th>
                <th className="hand" onClick={sort('pINBLOCKREMARKS')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINBLOCKREMARKS">P INBLOCKREMARKS</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINBLOCKREMARKS')} />
                </th>
                <th className="hand" onClick={sort('pINRESETBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETBY">P INRESETBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINRESETBY')} />
                </th>
                <th className="hand" onClick={sort('pINRESETON')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETON">P INRESETON</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINRESETON')} />
                </th>
                <th className="hand" onClick={sort('pINRESETAPPROVEDBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETAPPROVEDBY">P INRESETAPPROVEDBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINRESETAPPROVEDBY')} />
                </th>
                <th className="hand" onClick={sort('pINRESETAPPROVEDON')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETAPPROVEDON">P INRESETAPPROVEDON</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINRESETAPPROVEDON')} />
                </th>
                <th className="hand" onClick={sort('pINRESETREMARKS')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.pINRESETREMARKS">P INRESETREMARKS</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pINRESETREMARKS')} />
                </th>
                <th className="hand" onClick={sort('bRANCHCODE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.bRANCHCODE">B RANCHCODE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('bRANCHCODE')} />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {pINRESETHISTORYList.map((pINRESETHISTORY, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/pinresethistory/${pINRESETHISTORY.id}`} color="link" size="sm">
                      {pINRESETHISTORY.id}
                    </Button>
                  </td>
                  <td>{pINRESETHISTORY.pHONENUMBER}</td>
                  <td>{pINRESETHISTORY.cUSTOMERNAME}</td>
                  <td>{pINRESETHISTORY.pINBLOCKEDON}</td>
                  <td>{pINRESETHISTORY.pINBLOCKREMARKS}</td>
                  <td>{pINRESETHISTORY.pINRESETBY}</td>
                  <td>{pINRESETHISTORY.pINRESETON}</td>
                  <td>{pINRESETHISTORY.pINRESETAPPROVEDBY}</td>
                  <td>{pINRESETHISTORY.pINRESETAPPROVEDON}</td>
                  <td>{pINRESETHISTORY.pINRESETREMARKS}</td>
                  <td>{pINRESETHISTORY.bRANCHCODE}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button tag={Link} to={`/pinresethistory/${pINRESETHISTORY.id}`} color="info" size="sm" data-cy="entityDetailsButton">
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/pinresethistory/${pINRESETHISTORY.id}/edit`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() => (window.location.href = `/pinresethistory/${pINRESETHISTORY.id}/delete`)}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="bbMobileBankingAdminApp.pINRESETHISTORY.home.notFound">No PINRESETHISTORIES found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default PINRESETHISTORY;
