// src/main/webapp/app/entities/servicemanagement/servicemanagement.tsx
import React, { useEffect, useState } from 'react';
import { Link, useLocation, useNavigate } from 'react-router-dom';
import { Button, Table } from 'reactstrap';
import { TextFormat, Translate, getSortState } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';
import { faSort, faSortDown, faSortUp } from '@fortawesome/free-solid-svg-icons';
import { APP_DATE_FORMAT } from 'app/config/constants';
import { ASC, DESC } from 'app/shared/util/pagination.constants';
import { overrideSortStateWithQueryParams } from 'app/shared/util/entity-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities } from './servicemanagement.reducer';

export const SERVICEMANAGEMENT = () => {
  const dispatch = useAppDispatch();

  const pageLocation = useLocation();
  const navigate = useNavigate();

  const [sortState, setSortState] = useState(overrideSortStateWithQueryParams(getSortState(pageLocation, 'id'), pageLocation.search));

  const sERVICEMANAGEMENTList = useAppSelector(state => state.sERVICEMANAGEMENT.entities);
  const loading = useAppSelector(state => state.sERVICEMANAGEMENT.loading);

  const getAllEntities = () => {
    dispatch(
      getEntities({
        sort: `${sortState.sort},${sortState.order}`,
      }),
    );
  };

  const sortEntities = () => {
    getAllEntities();
    const endURL = `?sort=${sortState.sort},${sortState.order}`;
    if (pageLocation.search !== endURL) {
      navigate(`${pageLocation.pathname}${endURL}`);
    }
  };

  useEffect(() => {
    sortEntities();
  }, [sortState.order, sortState.sort]);

  const sort = p => () => {
    setSortState({
      ...sortState,
      order: sortState.order === ASC ? DESC : ASC,
      sort: p,
    });
  };

  const handleSyncList = () => {
    sortEntities();
  };

  const getSortIconByFieldName = (fieldName: string) => {
    const sortFieldName = sortState.sort;
    const order = sortState.order;
    if (sortFieldName !== fieldName) {
      return faSort;
    }
    return order === ASC ? faSortUp : faSortDown;
  };

  return (
    <div>
      <h2 id="servicemanagement-heading" data-cy="SERVICEMANAGEMENTHeading">
        <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.home.title">SERVICEMANAGEMENTS</Translate>
        <div className="d-flex justify-content-end">
          <Button className="me-2" color="info" onClick={handleSyncList} disabled={loading}>
            <FontAwesomeIcon icon="sync" spin={loading} />{' '}
            <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.home.refreshListLabel">Refresh List</Translate>
          </Button>
          <Link to="/servicemanagement/new" className="btn btn-primary jh-create-entity" id="jh-create-entity" data-cy="entityCreateButton">
            <FontAwesomeIcon icon="plus" />
            &nbsp;
            <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.home.createLabel">Create new SERVICEMANAGEMENT</Translate>
          </Link>
        </div>
      </h2>
      <div className="table-responsive">
        {sERVICEMANAGEMENTList && sERVICEMANAGEMENTList.length > 0 ? (
          <Table responsive>
            <thead>
              <tr>
                <th className="hand" onClick={sort('id')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.id">ID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('id')} />
                </th>
                <th className="hand" onClick={sort('pROCESSINGCODE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.pROCESSINGCODE">P ROCESSINGCODE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('pROCESSINGCODE')} />
                </th>
                <th className="hand" onClick={sort('aCTIVE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.aCTIVE">A CTIVE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aCTIVE')} />
                </th>
                <th className="hand" onClick={sort('cREATEDBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.cREATEDBY">C REATEDBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('cREATEDBY')} />
                </th>
                <th className="hand" onClick={sort('dATECREATED')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.dATECREATED">D ATECREATED</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('dATECREATED')} />
                </th>
                <th className="hand" onClick={sort('aPPROVED')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.aPPROVED">A PPROVED</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aPPROVED')} />
                </th>
                <th className="hand" onClick={sort('aPPROVEDBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.aPPROVEDBY">A PPROVEDBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aPPROVEDBY')} />
                </th>
                <th className="hand" onClick={sort('aPPROVEDDATE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.aPPROVEDDATE">A PPROVEDDATE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aPPROVEDDATE')} />
                </th>
                <th className="hand" onClick={sort('aDAPTORTYPE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.aDAPTORTYPE">A DAPTORTYPE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('aDAPTORTYPE')} />
                </th>
                <th className="hand" onClick={sort('dESTINATION')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.dESTINATION">D ESTINATION</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('dESTINATION')} />
                </th>
                <th className="hand" onClick={sort('tHIRDPARTYRESPONSE')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.tHIRDPARTYRESPONSE">T HIRDPARTYRESPONSE</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('tHIRDPARTYRESPONSE')} />
                </th>
                <th className="hand" onClick={sort('tELCO')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.tELCO">T ELCO</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('tELCO')} />
                </th>
                <th className="hand" onClick={sort('dESCRIPTION')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.dESCRIPTION">D ESCRIPTION</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('dESCRIPTION')} />
                </th>
                <th className="hand" onClick={sort('rEMARKS')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.rEMARKS">R EMARKS</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('rEMARKS')} />
                </th>
                <th className="hand" onClick={sort('sESSIONID')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.sESSIONID">S ESSIONID</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('sESSIONID')} />
                </th>
                <th className="hand" onClick={sort('rEWORKBY')}>
                  <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.rEWORKBY">R EWORKBY</Translate>{' '}
                  <FontAwesomeIcon icon={getSortIconByFieldName('rEWORKBY')} />
                </th>
                <th />
              </tr>
            </thead>
            <tbody>
              {sERVICEMANAGEMENTList.map((sERVICEMANAGEMENT, i) => (
                <tr key={`entity-${i}`} data-cy="entityTable">
                  <td>
                    <Button tag={Link} to={`/servicemanagement/${sERVICEMANAGEMENT.id}`} color="link" size="sm">
                      {sERVICEMANAGEMENT.id}
                    </Button>
                  </td>
                  <td>{sERVICEMANAGEMENT.pROCESSINGCODE}</td>
                  <td>{sERVICEMANAGEMENT.aCTIVE}</td>
                  <td>{sERVICEMANAGEMENT.cREATEDBY}</td>
                  <td>
                    {sERVICEMANAGEMENT.dATECREATED ? (
                      <TextFormat type="date" value={sERVICEMANAGEMENT.dATECREATED} format={APP_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>{sERVICEMANAGEMENT.aPPROVED}</td>
                  <td>{sERVICEMANAGEMENT.aPPROVEDBY}</td>
                  <td>
                    {sERVICEMANAGEMENT.aPPROVEDDATE ? (
                      <TextFormat type="date" value={sERVICEMANAGEMENT.aPPROVEDDATE} format={APP_DATE_FORMAT} />
                    ) : null}
                  </td>
                  <td>{sERVICEMANAGEMENT.aDAPTORTYPE}</td>
                  <td>{sERVICEMANAGEMENT.dESTINATION}</td>
                  <td>{sERVICEMANAGEMENT.tHIRDPARTYRESPONSE}</td>
                  <td>{sERVICEMANAGEMENT.tELCO}</td>
                  <td>{sERVICEMANAGEMENT.dESCRIPTION}</td>
                  <td>{sERVICEMANAGEMENT.rEMARKS}</td>
                  <td>{sERVICEMANAGEMENT.sESSIONID}</td>
                  <td>{sERVICEMANAGEMENT.rEWORKBY}</td>
                  <td className="text-end">
                    <div className="btn-group flex-btn-group-container">
                      <Button
                        tag={Link}
                        to={`/servicemanagement/${sERVICEMANAGEMENT.id}`}
                        color="info"
                        size="sm"
                        data-cy="entityDetailsButton"
                      >
                        <FontAwesomeIcon icon="eye" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.view">View</Translate>
                        </span>
                      </Button>
                      <Button
                        tag={Link}
                        to={`/servicemanagement/${sERVICEMANAGEMENT.id}/edit`}
                        color="primary"
                        size="sm"
                        data-cy="entityEditButton"
                      >
                        <FontAwesomeIcon icon="pencil-alt" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.edit">Edit</Translate>
                        </span>
                      </Button>
                      <Button
                        onClick={() => (window.location.href = `/servicemanagement/${sERVICEMANAGEMENT.id}/delete`)}
                        color="danger"
                        size="sm"
                        data-cy="entityDeleteButton"
                      >
                        <FontAwesomeIcon icon="trash" />{' '}
                        <span className="d-none d-md-inline">
                          <Translate contentKey="entity.action.delete">Delete</Translate>
                        </span>
                      </Button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </Table>
        ) : (
          !loading && (
            <div className="alert alert-warning">
              <Translate contentKey="bbMobileBankingAdminApp.sERVICEMANAGEMENT.home.notFound">No SERVICEMANAGEMENTS found</Translate>
            </div>
          )
        )}
      </div>
    </div>
  );
};

export default SERVICEMANAGEMENT;

// src/main/webapp/app/entities/service-management/service-management.vue
<template>
  <div>
    <h2 id="page-heading" data-cy="ServiceManagementHeading">
      <span v-text="t$('bbMobileBankingAdminApp.serviceManagement.home.title')" id="service-management-heading"></span>
      <div class="d-flex justify-content-end">
        <button class="btn btn-info mr-2" @click="handleSyncList" :disabled="isFetching">
          <font-awesome-icon icon="sync" :spin="isFetching"></font-awesome-icon>
          <span v-text="t$('bbMobileBankingAdminApp.serviceManagement.home.refreshListLabel')"></span>
        </button>
        <!-- <router-link :to="{ name: 'ServiceManagementCreate' }" custom v-slot="{ navigate }">
          <button
            @click="navigate"
            id="jh-create-entity"
            data-cy="entityCreateButton"
            class="btn btn-primary jh-create-entity create-service-management"
          >
            <font-awesome-icon icon="plus"></font-awesome-icon>
            <span v-text="t$('bbMobileBankingAdminApp.serviceManagement.home.createLabel')"></span>
          </button>
        </router-link> -->
      </div>
    </h2>
    <br />
    <div class="alert alert-warning" v-if="!isFetching && serviceManagements && serviceManagements.length === 0">
      <span v-text="t$('bbMobileBankingAdminApp.serviceManagement.home.notFound')"></span>
    </div>
    <div class="table-responsive" v-if="serviceManagements && serviceManagements.length > 0">
      <table class="table table-striped" aria-describedby="serviceManagements">
        <thead>
          <tr>
            <th scope="row"><span v-text="t$('global.field.id')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.processingcode')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.active')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.createdby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.datecreated')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.approved')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.approvedby')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.approveddate')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.adaptortype')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.destination')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.thirdpartyresponse')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.telco')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.description')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.remarks')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.sessionid')"></span></th>
            <th scope="row"><span v-text="t$('bbMobileBankingAdminApp.serviceManagement.reworkby')"></span></th>
            <th scope="row"></th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="serviceManagement in serviceManagements" :key="serviceManagement.id" data-cy="entityTable">
            <td>
              <router-link :to="{ name: 'ServiceManagementView', params: { serviceManagementId: serviceManagement.id } }">{{
                serviceManagement.id
              }}</router-link>
            </td>
            <td>{{ serviceManagement.processingcode }}</td>
            <td>{{ serviceManagement.active }}</td>
            <td>{{ serviceManagement.createdby }}</td>
            <td>{{ formatDateShort(serviceManagement.datecreated) || '' }}</td>
            <td>{{ serviceManagement.approved }}</td>
            <td>{{ serviceManagement.approvedby }}</td>
            <td>{{ formatDateShort(serviceManagement.approveddate) || '' }}</td>
            <td>{{ serviceManagement.adaptortype }}</td>
            <td>{{ serviceManagement.destination }}</td>
            <td>{{ serviceManagement.thirdpartyresponse }}</td>
            <td>{{ serviceManagement.telco }}</td>
            <td>{{ serviceManagement.description }}</td>
            <td>{{ serviceManagement.remarks }}</td>
            <td>{{ serviceManagement.sessionid }}</td>
            <td>{{ serviceManagement.reworkby }}</td>
            <td class="text-right">
              <div class="btn-group">
                <router-link
                  :to="{ name: 'ServiceManagementView', params: { serviceManagementId: serviceManagement.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-info btn-sm details" data-cy="entityDetailsButton">
                    <font-awesome-icon icon="eye"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="t$('entity.action.view')"></span>
                  </button>
                </router-link>
                <!-- <router-link
                  :to="{ name: 'ServiceManagementEdit', params: { serviceManagementId: serviceManagement.id } }"
                  custom
                  v-slot="{ navigate }"
                >
                  <button @click="navigate" class="btn btn-primary btn-sm edit" data-cy="entityEditButton">
                    <font-awesome-icon icon="pencil-alt"></font-awesome-icon>
                    <span class="d-none d-md-inline" v-text="t$('entity.action.edit')"></span>
                  </button>
                </router-link> -->
                <!-- <b-button
                  @click="prepareRemove(serviceManagement)"
                  variant="danger"
                  class="btn btn-sm"
                  data-cy="entityDeleteButton"
                  v-b-modal.removeEntity
                >
                  <font-awesome-icon icon="times"></font-awesome-icon>
                  <span class="d-none d-md-inline" v-text="t$('entity.action.delete')"></span>
                </b-button> -->
              </div>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <b-modal ref="removeEntity" id="removeEntity">
      <template #modal-title>
        <span
          id="bbMobileBankingAdminApp.serviceManagement.delete.question"
          data-cy="serviceManagementDeleteDialogHeading"
          v-text="t$('entity.delete.title')"
        ></span>
      </template>
      <div class="modal-body">
        <p
          id="jhi-delete-serviceManagement-heading"
          v-text="t$('bbMobileBankingAdminApp.serviceManagement.delete.question', { id: removeId })"
        ></p>
      </div>
      <template #modal-footer>
        <div>
          <button type="button" class="btn btn-secondary" v-text="t$('entity.action.cancel')" @click="closeDialog()"></button>
          <button
            type="button"
            class="btn btn-primary"
            id="jhi-confirm-delete-serviceManagement"
            data-cy="entityConfirmDeleteButton"
            v-text="t$('entity.action.delete')"
            @click="removeServiceManagement()"
          ></button>
        </div>
      </template>
    </b-modal>
  </div>
</template>

<script lang="ts" src="./service-management.component.ts"></script>
