// src/main/webapp/app/entities/charge/charge-update.tsx
import React, { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate, ValidatedField, ValidatedForm, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntities as getCHARGERANGES } from 'app/entities/chargeranges/chargeranges.reducer';
import { getEntities as getRANGES } from 'app/entities/range/range.reducer';
import { createEntity, getEntity, reset, updateEntity } from './charge.reducer';

export const CHARGEUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const cHARGERANGES = useAppSelector(state => state.cHARGERANGES.entities);
  const rANGES = useAppSelector(state => state.rANGE.entities);
  const cHARGEEntity = useAppSelector(state => state.cHARGE.entity);
  const loading = useAppSelector(state => state.cHARGE.loading);
  const updating = useAppSelector(state => state.cHARGE.updating);
  const updateSuccess = useAppSelector(state => state.cHARGE.updateSuccess);

  const handleClose = () => {
    navigate('/charge');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }

    dispatch(getCHARGERANGES({}));
    dispatch(getRANGES({}));
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }
    if (values.fEEMODE !== undefined && typeof values.fEEMODE !== 'number') {
      values.fEEMODE = Number(values.fEEMODE);
    }
    if (values.aMOUNT !== undefined && typeof values.aMOUNT !== 'number') {
      values.aMOUNT = Number(values.aMOUNT);
    }
    values.dATECREATED = convertDateTimeToServer(values.dATECREATED);
    if (values.tXNCODE !== undefined && typeof values.tXNCODE !== 'number') {
      values.tXNCODE = Number(values.tXNCODE);
    }
    values.aPPROVEDDATE = convertDateTimeToServer(values.aPPROVEDDATE);

    const entity = {
      ...cHARGEEntity,
      ...values,
      cHARGERANGES: cHARGERANGES.find(it => it.id.toString() === values.cHARGERANGES?.toString()),
      rANGE: rANGES.find(it => it.id.toString() === values.rANGE?.toString()),
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          dATECREATED: displayDefaultDateTime(),
          aPPROVEDDATE: displayDefaultDateTime(),
        }
      : {
          ...cHARGEEntity,
          dATECREATED: convertDateTimeFromServer(cHARGEEntity.dATECREATED),
          aPPROVEDDATE: convertDateTimeFromServer(cHARGEEntity.aPPROVEDDATE),
          cHARGERANGES: cHARGEEntity?.cHARGERANGES?.id,
          rANGE: cHARGEEntity?.rANGE?.id,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="bbMobileBankingAdminApp.cHARGE.home.createOrEditLabel" data-cy="CHARGECreateUpdateHeading">
            <Translate contentKey="bbMobileBankingAdminApp.cHARGE.home.createOrEditLabel">Create or edit a CHARGE</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="charge-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.tXNTYPE')}
                id="charge-tXNTYPE"
                name="tXNTYPE"
                data-cy="tXNTYPE"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  maxLength: { value: 150, message: translate('entity.validation.maxlength', { max: 150 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.fEEMODE')}
                id="charge-fEEMODE"
                name="fEEMODE"
                data-cy="fEEMODE"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.aMOUNT')}
                id="charge-aMOUNT"
                name="aMOUNT"
                data-cy="aMOUNT"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.dATECREATED')}
                id="charge-dATECREATED"
                name="dATECREATED"
                data-cy="dATECREATED"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.cREATEDBY')}
                id="charge-cREATEDBY"
                name="cREATEDBY"
                data-cy="cREATEDBY"
                type="text"
                validate={{
                  maxLength: { value: 150, message: translate('entity.validation.maxlength', { max: 150 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.aPPROVED')}
                id="charge-aPPROVED"
                name="aPPROVED"
                data-cy="aPPROVED"
                type="text"
                validate={{
                  maxLength: { value: 150, message: translate('entity.validation.maxlength', { max: 150 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.aPPROVEDBY')}
                id="charge-aPPROVEDBY"
                name="aPPROVEDBY"
                data-cy="aPPROVEDBY"
                type="text"
                validate={{
                  maxLength: { value: 150, message: translate('entity.validation.maxlength', { max: 150 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.cHANNEL')}
                id="charge-cHANNEL"
                name="cHANNEL"
                data-cy="cHANNEL"
                type="text"
                validate={{
                  maxLength: { value: 150, message: translate('entity.validation.maxlength', { max: 150 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.tXNCODE')}
                id="charge-tXNCODE"
                name="tXNCODE"
                data-cy="tXNCODE"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.dESCRIPTION')}
                id="charge-dESCRIPTION"
                name="dESCRIPTION"
                data-cy="dESCRIPTION"
                type="text"
                validate={{
                  maxLength: { value: 64, message: translate('entity.validation.maxlength', { max: 64 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cHARGE.aPPROVEDDATE')}
                id="charge-aPPROVEDDATE"
                name="aPPROVEDDATE"
                data-cy="aPPROVEDDATE"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                id="charge-cHARGERANGES"
                name="cHARGERANGES"
                data-cy="cHARGERANGES"
                label={translate('bbMobileBankingAdminApp.cHARGE.cHARGERANGES')}
                type="select"
              >
                <option value="" key="0" />
                {cHARGERANGES
                  ? cHARGERANGES.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <ValidatedField
                id="charge-rANGE"
                name="rANGE"
                data-cy="rANGE"
                label={translate('bbMobileBankingAdminApp.cHARGE.rANGE')}
                type="select"
              >
                <option value="" key="0" />
                {rANGES
                  ? rANGES.map(otherEntity => (
                      <option value={otherEntity.id} key={otherEntity.id}>
                        {otherEntity.id}
                      </option>
                    ))
                  : null}
              </ValidatedField>
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/charge" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default CHARGEUpdate;

// src/main/webapp/app/entities/charge/charge-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" novalidate @submit.prevent="save()">
        <h2
          id="bbMobileBankingAdminApp.charge.home.createOrEditLabel"
          data-cy="ChargeCreateUpdateHeading"
          v-text="t$('bbMobileBankingAdminApp.charge.home.createOrEditLabel')"
        ></h2>
        <div>
          <div class="form-group" v-if="charge.id">
            <label for="id" v-text="t$('global.field.id')"></label>
            <input type="text" class="form-control" id="id" name="id" v-model="charge.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.txntype')" for="charge-txntype"></label>
            <input
              type="text"
              class="form-control"
              name="txntype"
              id="charge-txntype"
              data-cy="txntype"
              :class="{ valid: !v$.txntype.$invalid, invalid: v$.txntype.$invalid }"
              v-model="v$.txntype.$model"
              required
            />
            <div v-if="v$.txntype.$anyDirty && v$.txntype.$invalid">
              <small class="form-text text-danger" v-for="error of v$.txntype.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.feemode')" for="charge-feemode"></label>
            <input
              type="number"
              class="form-control"
              name="feemode"
              id="charge-feemode"
              data-cy="feemode"
              :class="{ valid: !v$.feemode.$invalid, invalid: v$.feemode.$invalid }"
              v-model.number="v$.feemode.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.amount')" for="charge-amount"></label>
            <input
              type="number"
              class="form-control"
              name="amount"
              id="charge-amount"
              data-cy="amount"
              :class="{ valid: !v$.amount.$invalid, invalid: v$.amount.$invalid }"
              v-model.number="v$.amount.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.datecreated')" for="charge-datecreated"></label>
            <div class="d-flex">
              <input
                id="charge-datecreated"
                data-cy="datecreated"
                type="datetime-local"
                class="form-control"
                name="datecreated"
                :class="{ valid: !v$.datecreated.$invalid, invalid: v$.datecreated.$invalid }"
                :value="convertDateTimeFromServer(v$.datecreated.$model)"
                @change="updateInstantField('datecreated', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.createdby')" for="charge-createdby"></label>
            <input
              type="text"
              class="form-control"
              name="createdby"
              id="charge-createdby"
              data-cy="createdby"
              :class="{ valid: !v$.createdby.$invalid, invalid: v$.createdby.$invalid }"
              v-model="v$.createdby.$model"
            />
            <div v-if="v$.createdby.$anyDirty && v$.createdby.$invalid">
              <small class="form-text text-danger" v-for="error of v$.createdby.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.approved')" for="charge-approved"></label>
            <input
              type="text"
              class="form-control"
              name="approved"
              id="charge-approved"
              data-cy="approved"
              :class="{ valid: !v$.approved.$invalid, invalid: v$.approved.$invalid }"
              v-model="v$.approved.$model"
            />
            <div v-if="v$.approved.$anyDirty && v$.approved.$invalid">
              <small class="form-text text-danger" v-for="error of v$.approved.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.approvedby')" for="charge-approvedby"></label>
            <input
              type="text"
              class="form-control"
              name="approvedby"
              id="charge-approvedby"
              data-cy="approvedby"
              :class="{ valid: !v$.approvedby.$invalid, invalid: v$.approvedby.$invalid }"
              v-model="v$.approvedby.$model"
            />
            <div v-if="v$.approvedby.$anyDirty && v$.approvedby.$invalid">
              <small class="form-text text-danger" v-for="error of v$.approvedby.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.channel')" for="charge-channel"></label>
            <input
              type="text"
              class="form-control"
              name="channel"
              id="charge-channel"
              data-cy="channel"
              :class="{ valid: !v$.channel.$invalid, invalid: v$.channel.$invalid }"
              v-model="v$.channel.$model"
            />
            <div v-if="v$.channel.$anyDirty && v$.channel.$invalid">
              <small class="form-text text-danger" v-for="error of v$.channel.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.txncode')" for="charge-txncode"></label>
            <input
              type="number"
              class="form-control"
              name="txncode"
              id="charge-txncode"
              data-cy="txncode"
              :class="{ valid: !v$.txncode.$invalid, invalid: v$.txncode.$invalid }"
              v-model.number="v$.txncode.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.description')" for="charge-description"></label>
            <input
              type="text"
              class="form-control"
              name="description"
              id="charge-description"
              data-cy="description"
              :class="{ valid: !v$.description.$invalid, invalid: v$.description.$invalid }"
              v-model="v$.description.$model"
            />
            <div v-if="v$.description.$anyDirty && v$.description.$invalid">
              <small class="form-text text-danger" v-for="error of v$.description.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.approveddate')" for="charge-approveddate"></label>
            <div class="d-flex">
              <input
                id="charge-approveddate"
                data-cy="approveddate"
                type="datetime-local"
                class="form-control"
                name="approveddate"
                :class="{ valid: !v$.approveddate.$invalid, invalid: v$.approveddate.$invalid }"
                :value="convertDateTimeFromServer(v$.approveddate.$model)"
                @change="updateInstantField('approveddate', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.chargeRange')" for="charge-chargeRange"></label>
            <select class="form-control" id="charge-chargeRange" data-cy="chargeRange" name="chargeRange" v-model="charge.chargeRange">
              <option :value="null"></option>
              <option
                :value="charge.chargeRange && chargeRangeOption.id === charge.chargeRange.id ? charge.chargeRange : chargeRangeOption"
                v-for="chargeRangeOption in chargeRanges"
                :key="chargeRangeOption.id"
              >
                {{ chargeRangeOption.id }}
              </option>
            </select>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.charge.range')" for="charge-range"></label>
            <select class="form-control" id="charge-range" data-cy="range" name="range" v-model="charge.range">
              <option :value="null"></option>
              <option
                :value="charge.range && rangeOption.id === charge.range.id ? charge.range : rangeOption"
                v-for="rangeOption in ranges"
                :key="rangeOption.id"
              >
                {{ rangeOption.id }}
              </option>
            </select>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" @click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.cancel')"></span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="v$.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.save')"></span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./charge-update.component.ts"></script>
