// src/main/webapp/app/entities/customer-account/customer-account-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" novalidate @submit.prevent="save()">
        <h2
          id="bbMobileBankingAdminApp.customerAccount.home.createOrEditLabel"
          data-cy="CustomerAccountCreateUpdateHeading"
          v-text="t$('bbMobileBankingAdminApp.customerAccount.home.createOrEditLabel')"
        ></h2>
        <div>
          <div class="form-group" v-if="customerAccount.id">
            <label for="id" v-text="t$('global.field.id')"></label>
            <input type="text" class="form-control" id="id" name="id" v-model="customerAccount.id" readonly />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.customerid')"
              for="customer-account-customerid"
            ></label>
            <input
              type="number"
              class="form-control"
              name="customerid"
              id="customer-account-customerid"
              data-cy="customerid"
              :class="{ valid: !v$.customerid.$invalid, invalid: v$.customerid.$invalid }"
              v-model.number="v$.customerid.$model"
              required
            />
            <div v-if="v$.customerid.$anyDirty && v$.customerid.$invalid">
              <small class="form-text text-danger" v-for="error of v$.customerid.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.accountnumber')"
              for="customer-account-accountnumber"
            ></label>
            <input
              type="text"
              class="form-control"
              name="accountnumber"
              id="customer-account-accountnumber"
              data-cy="accountnumber"
              :class="{ valid: !v$.accountnumber.$invalid, invalid: v$.accountnumber.$invalid }"
              v-model="v$.accountnumber.$model"
              required
            />
            <div v-if="v$.accountnumber.$anyDirty && v$.accountnumber.$invalid">
              <small class="form-text text-danger" v-for="error of v$.accountnumber.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.accountclass')"
              for="customer-account-accountclass"
            ></label>
            <input
              type="text"
              class="form-control"
              name="accountclass"
              id="customer-account-accountclass"
              data-cy="accountclass"
              :class="{ valid: !v$.accountclass.$invalid, invalid: v$.accountclass.$invalid }"
              v-model="v$.accountclass.$model"
            />
            <div v-if="v$.accountclass.$anyDirty && v$.accountclass.$invalid">
              <small class="form-text text-danger" v-for="error of v$.accountclass.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.customernumber')"
              for="customer-account-customernumber"
            ></label>
            <input
              type="text"
              class="form-control"
              name="customernumber"
              id="customer-account-customernumber"
              data-cy="customernumber"
              :class="{ valid: !v$.customernumber.$invalid, invalid: v$.customernumber.$invalid }"
              v-model="v$.customernumber.$model"
            />
            <div v-if="v$.customernumber.$anyDirty && v$.customernumber.$invalid">
              <small class="form-text text-danger" v-for="error of v$.customernumber.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.customerAccount.cif')" for="customer-account-cif"></label>
            <input
              type="text"
              class="form-control"
              name="cif"
              id="customer-account-cif"
              data-cy="cif"
              :class="{ valid: !v$.cif.$invalid, invalid: v$.cif.$invalid }"
              v-model="v$.cif.$model"
              required
            />
            <div v-if="v$.cif.$anyDirty && v$.cif.$invalid">
              <small class="form-text text-danger" v-for="error of v$.cif.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.timelinked')"
              for="customer-account-timelinked"
            ></label>
            <div class="d-flex">
              <input
                id="customer-account-timelinked"
                data-cy="timelinked"
                type="datetime-local"
                class="form-control"
                name="timelinked"
                :class="{ valid: !v$.timelinked.$invalid, invalid: v$.timelinked.$invalid }"
                :value="convertDateTimeFromServer(v$.timelinked.$model)"
                @change="updateInstantField('timelinked', $event)"
              />
            </div>
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.blocked')"
              for="customer-account-blocked"
            ></label>
            <input
              type="number"
              class="form-control"
              name="blocked"
              id="customer-account-blocked"
              data-cy="blocked"
              :class="{ valid: !v$.blocked.$invalid, invalid: v$.blocked.$invalid }"
              v-model.number="v$.blocked.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.stopped')"
              for="customer-account-stopped"
            ></label>
            <input
              type="number"
              class="form-control"
              name="stopped"
              id="customer-account-stopped"
              data-cy="stopped"
              :class="{ valid: !v$.stopped.$invalid, invalid: v$.stopped.$invalid }"
              v-model.number="v$.stopped.$model"
            />
          </div>
          <div class="form-group">
            <label
              class="form-control-label"
              v-text="t$('bbMobileBankingAdminApp.customerAccount.dormant')"
              for="customer-account-dormant"
            ></label>
            <input
              type="number"
              class="form-control"
              name="dormant"
              id="customer-account-dormant"
              data-cy="dormant"
              :class="{ valid: !v$.dormant.$invalid, invalid: v$.dormant.$invalid }"
              v-model.number="v$.dormant.$model"
            />
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" @click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.cancel')"></span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="v$.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.save')"></span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./customer-account-update.component.ts"></script>

// src/main/webapp/app/entities/customeraccount/customeraccount-update.tsx
import React, { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate, ValidatedField, ValidatedForm, isNumber, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { convertDateTimeFromServer, convertDateTimeToServer, displayDefaultDateTime } from 'app/shared/util/date-utils';
import { useAppDispatch, useAppSelector } from 'app/config/store';

import { createEntity, getEntity, reset, updateEntity } from './customeraccount.reducer';

export const CUSTOMERACCOUNTUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const cUSTOMERACCOUNTEntity = useAppSelector(state => state.cUSTOMERACCOUNT.entity);
  const loading = useAppSelector(state => state.cUSTOMERACCOUNT.loading);
  const updating = useAppSelector(state => state.cUSTOMERACCOUNT.updating);
  const updateSuccess = useAppSelector(state => state.cUSTOMERACCOUNT.updateSuccess);

  const handleClose = () => {
    navigate('/customeraccount');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }
    if (values.cUSTOMERID !== undefined && typeof values.cUSTOMERID !== 'number') {
      values.cUSTOMERID = Number(values.cUSTOMERID);
    }
    values.tIMELINKED = convertDateTimeToServer(values.tIMELINKED);
    if (values.bLOCKED !== undefined && typeof values.bLOCKED !== 'number') {
      values.bLOCKED = Number(values.bLOCKED);
    }
    if (values.sTOPPED !== undefined && typeof values.sTOPPED !== 'number') {
      values.sTOPPED = Number(values.sTOPPED);
    }
    if (values.dORMANT !== undefined && typeof values.dORMANT !== 'number') {
      values.dORMANT = Number(values.dORMANT);
    }

    const entity = {
      ...cUSTOMERACCOUNTEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {
          tIMELINKED: displayDefaultDateTime(),
        }
      : {
          ...cUSTOMERACCOUNTEntity,
          tIMELINKED: convertDateTimeFromServer(cUSTOMERACCOUNTEntity.tIMELINKED),
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="bbMobileBankingAdminApp.cUSTOMERACCOUNT.home.createOrEditLabel" data-cy="CUSTOMERACCOUNTCreateUpdateHeading">
            <Translate contentKey="bbMobileBankingAdminApp.cUSTOMERACCOUNT.home.createOrEditLabel">
              Create or edit a CUSTOMERACCOUNT
            </Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="customeraccount-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.cUSTOMERID')}
                id="customeraccount-cUSTOMERID"
                name="cUSTOMERID"
                data-cy="cUSTOMERID"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  validate: v => isNumber(v) || translate('entity.validation.number'),
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.aCCOUNTNUMBER')}
                id="customeraccount-aCCOUNTNUMBER"
                name="aCCOUNTNUMBER"
                data-cy="aCCOUNTNUMBER"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  maxLength: { value: 11, message: translate('entity.validation.maxlength', { max: 11 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.aCCOUNTCLASS')}
                id="customeraccount-aCCOUNTCLASS"
                name="aCCOUNTCLASS"
                data-cy="aCCOUNTCLASS"
                type="text"
                validate={{
                  maxLength: { value: 10, message: translate('entity.validation.maxlength', { max: 10 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.cUSTOMERNUMBER')}
                id="customeraccount-cUSTOMERNUMBER"
                name="cUSTOMERNUMBER"
                data-cy="cUSTOMERNUMBER"
                type="text"
                validate={{
                  maxLength: { value: 20, message: translate('entity.validation.maxlength', { max: 20 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.cIF')}
                id="customeraccount-cIF"
                name="cIF"
                data-cy="cIF"
                type="text"
                validate={{
                  required: { value: true, message: translate('entity.validation.required') },
                  maxLength: { value: 20, message: translate('entity.validation.maxlength', { max: 20 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.tIMELINKED')}
                id="customeraccount-tIMELINKED"
                name="tIMELINKED"
                data-cy="tIMELINKED"
                type="datetime-local"
                placeholder="YYYY-MM-DD HH:mm"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.bLOCKED')}
                id="customeraccount-bLOCKED"
                name="bLOCKED"
                data-cy="bLOCKED"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.sTOPPED')}
                id="customeraccount-sTOPPED"
                name="sTOPPED"
                data-cy="sTOPPED"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.cUSTOMERACCOUNT.dORMANT')}
                id="customeraccount-dORMANT"
                name="dORMANT"
                data-cy="dORMANT"
                type="text"
              />
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/customeraccount" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default CUSTOMERACCOUNTUpdate;
