// src/main/webapp/app/entities/range/range-update.vue
<template>
  <div class="row justify-content-center">
    <div class="col-8">
      <form name="editForm" novalidate @submit.prevent="save()">
        <h2
          id="bbMobileBankingAdminApp.range.home.createOrEditLabel"
          data-cy="RangeCreateUpdateHeading"
          v-text="t$('bbMobileBankingAdminApp.range.home.createOrEditLabel')"
        ></h2>
        <div>
          <div class="form-group" v-if="range.id">
            <label for="id" v-text="t$('global.field.id')"></label>
            <input type="text" class="form-control" id="id" name="id" v-model="range.id" readonly />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.rangefrom')" for="range-rangefrom"></label>
            <input
              type="number"
              class="form-control"
              name="rangefrom"
              id="range-rangefrom"
              data-cy="rangefrom"
              :class="{ valid: !v$.rangefrom.$invalid, invalid: v$.rangefrom.$invalid }"
              v-model.number="v$.rangefrom.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.rangeto')" for="range-rangeto"></label>
            <input
              type="number"
              class="form-control"
              name="rangeto"
              id="range-rangeto"
              data-cy="rangeto"
              :class="{ valid: !v$.rangeto.$invalid, invalid: v$.rangeto.$invalid }"
              v-model.number="v$.rangeto.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.amount')" for="range-amount"></label>
            <input
              type="number"
              class="form-control"
              name="amount"
              id="range-amount"
              data-cy="amount"
              :class="{ valid: !v$.amount.$invalid, invalid: v$.amount.$invalid }"
              v-model.number="v$.amount.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.txntype')" for="range-txntype"></label>
            <input
              type="text"
              class="form-control"
              name="txntype"
              id="range-txntype"
              data-cy="txntype"
              :class="{ valid: !v$.txntype.$invalid, invalid: v$.txntype.$invalid }"
              v-model="v$.txntype.$model"
            />
            <div v-if="v$.txntype.$anyDirty && v$.txntype.$invalid">
              <small class="form-text text-danger" v-for="error of v$.txntype.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.txncode')" for="range-txncode"></label>
            <input
              type="text"
              class="form-control"
              name="txncode"
              id="range-txncode"
              data-cy="txncode"
              :class="{ valid: !v$.txncode.$invalid, invalid: v$.txncode.$invalid }"
              v-model="v$.txncode.$model"
            />
            <div v-if="v$.txncode.$anyDirty && v$.txncode.$invalid">
              <small class="form-text text-danger" v-for="error of v$.txncode.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.chargeid')" for="range-chargeid"></label>
            <input
              type="number"
              class="form-control"
              name="chargeid"
              id="range-chargeid"
              data-cy="chargeid"
              :class="{ valid: !v$.chargeid.$invalid, invalid: v$.chargeid.$invalid }"
              v-model.number="v$.chargeid.$model"
            />
          </div>
          <div class="form-group">
            <label class="form-control-label" v-text="t$('bbMobileBankingAdminApp.range.channel')" for="range-channel"></label>
            <input
              type="text"
              class="form-control"
              name="channel"
              id="range-channel"
              data-cy="channel"
              :class="{ valid: !v$.channel.$invalid, invalid: v$.channel.$invalid }"
              v-model="v$.channel.$model"
            />
            <div v-if="v$.channel.$anyDirty && v$.channel.$invalid">
              <small class="form-text text-danger" v-for="error of v$.channel.$errors" :key="error.$uid">{{ error.$message }}</small>
            </div>
          </div>
        </div>
        <div>
          <button type="button" id="cancel-save" data-cy="entityCreateCancelButton" class="btn btn-secondary" @click="previousState()">
            <font-awesome-icon icon="ban"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.cancel')"></span>
          </button>
          <button
            type="submit"
            id="save-entity"
            data-cy="entityCreateSaveButton"
            :disabled="v$.$invalid || isSaving"
            class="btn btn-primary"
          >
            <font-awesome-icon icon="save"></font-awesome-icon>&nbsp;<span v-text="t$('entity.action.save')"></span>
          </button>
        </div>
      </form>
    </div>
  </div>
</template>
<script lang="ts" src="./range-update.component.ts"></script>

// src/main/webapp/app/entities/range/range-update.tsx
import React, { useEffect } from 'react';
import { Link, useNavigate, useParams } from 'react-router-dom';
import { Button, Col, Row } from 'reactstrap';
import { Translate, ValidatedField, ValidatedForm, translate } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { createEntity, getEntity, reset, updateEntity } from './range.reducer';

export const RANGEUpdate = () => {
  const dispatch = useAppDispatch();

  const navigate = useNavigate();

  const { id } = useParams<'id'>();
  const isNew = id === undefined;

  const rANGEEntity = useAppSelector(state => state.rANGE.entity);
  const loading = useAppSelector(state => state.rANGE.loading);
  const updating = useAppSelector(state => state.rANGE.updating);
  const updateSuccess = useAppSelector(state => state.rANGE.updateSuccess);

  const handleClose = () => {
    navigate('/range');
  };

  useEffect(() => {
    if (isNew) {
      dispatch(reset());
    } else {
      dispatch(getEntity(id));
    }
  }, []);

  useEffect(() => {
    if (updateSuccess) {
      handleClose();
    }
  }, [updateSuccess]);

  const saveEntity = values => {
    if (values.id !== undefined && typeof values.id !== 'number') {
      values.id = Number(values.id);
    }
    if (values.rANGEFROM !== undefined && typeof values.rANGEFROM !== 'number') {
      values.rANGEFROM = Number(values.rANGEFROM);
    }
    if (values.rANGETO !== undefined && typeof values.rANGETO !== 'number') {
      values.rANGETO = Number(values.rANGETO);
    }
    if (values.aMOUNT !== undefined && typeof values.aMOUNT !== 'number') {
      values.aMOUNT = Number(values.aMOUNT);
    }
    if (values.cHARGEID !== undefined && typeof values.cHARGEID !== 'number') {
      values.cHARGEID = Number(values.cHARGEID);
    }

    const entity = {
      ...rANGEEntity,
      ...values,
    };

    if (isNew) {
      dispatch(createEntity(entity));
    } else {
      dispatch(updateEntity(entity));
    }
  };

  const defaultValues = () =>
    isNew
      ? {}
      : {
          ...rANGEEntity,
        };

  return (
    <div>
      <Row className="justify-content-center">
        <Col md="8">
          <h2 id="bbMobileBankingAdminApp.rANGE.home.createOrEditLabel" data-cy="RANGECreateUpdateHeading">
            <Translate contentKey="bbMobileBankingAdminApp.rANGE.home.createOrEditLabel">Create or edit a RANGE</Translate>
          </h2>
        </Col>
      </Row>
      <Row className="justify-content-center">
        <Col md="8">
          {loading ? (
            <p>Loading...</p>
          ) : (
            <ValidatedForm defaultValues={defaultValues()} onSubmit={saveEntity}>
              {!isNew ? (
                <ValidatedField
                  name="id"
                  required
                  readOnly
                  id="range-id"
                  label={translate('global.field.id')}
                  validate={{ required: true }}
                />
              ) : null}
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.rANGEFROM')}
                id="range-rANGEFROM"
                name="rANGEFROM"
                data-cy="rANGEFROM"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.rANGETO')}
                id="range-rANGETO"
                name="rANGETO"
                data-cy="rANGETO"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.aMOUNT')}
                id="range-aMOUNT"
                name="aMOUNT"
                data-cy="aMOUNT"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.tXNTYPE')}
                id="range-tXNTYPE"
                name="tXNTYPE"
                data-cy="tXNTYPE"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.tXNCODE')}
                id="range-tXNCODE"
                name="tXNCODE"
                data-cy="tXNCODE"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.cHARGEID')}
                id="range-cHARGEID"
                name="cHARGEID"
                data-cy="cHARGEID"
                type="text"
              />
              <ValidatedField
                label={translate('bbMobileBankingAdminApp.rANGE.cHANNEL')}
                id="range-cHANNEL"
                name="cHANNEL"
                data-cy="cHANNEL"
                type="text"
                validate={{
                  maxLength: { value: 50, message: translate('entity.validation.maxlength', { max: 50 }) },
                }}
              />
              <Button tag={Link} id="cancel-save" data-cy="entityCreateCancelButton" to="/range" replace color="info">
                <FontAwesomeIcon icon="arrow-left" />
                &nbsp;
                <span className="d-none d-md-inline">
                  <Translate contentKey="entity.action.back">Back</Translate>
                </span>
              </Button>
              &nbsp;
              <Button color="primary" id="save-entity" data-cy="entityCreateSaveButton" type="submit" disabled={updating}>
                <FontAwesomeIcon icon="save" />
                &nbsp;
                <Translate contentKey="entity.action.save">Save</Translate>
              </Button>
            </ValidatedForm>
          )}
        </Col>
      </Row>
    </div>
  );
};

export default RANGEUpdate;
